### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by Jayderp** [Sk1erLLC/20-20-20#1]
1. On a rare occurence, the game will crash with a java.util.ConcurrentModificationException
2. Pressing J then E creates a visual glitch in your inventory.

**Comment by ghost** [comment]
the `ConcurrentModificationException` sounds like an issue when you're unable to connect to our api
do you mind providing a crash report?

i've fixed the other issue though, thanks for letting us know

**Comment by Jayderp** [comment]
Sorry for the long delay. Here's the crash log I had.
https://pastebin.com/TEwqjaAQ

**Comment by ghost** [comment]
Should be fixed in https://github.com/Sk1erLLC/20-20-20/commit/acb7cc47aa4249291bf5ca3e09ccb94c54c59891, report back to me when possible.
